### PR TITLE
Added support for CAT24C02/04/08/16 devices

### PR DESCRIPTION
**Pull request by Bu-Gee**
I finally got around to back-porting in the compatibility of the original library into the fork.

I don't have one of the 16-bit addressing I2C devices to test with though, so I hope that I didn't break anything.

### CODE REVIEW

**Comment by QuentinCG** [comment]
Thanks for this incredible PR !

I did a rapid source code read and it seems to not break previously supported EEPROMs.
I'll have more time next week to be sure of that before merging it.
Once merged, I'll will do some minor edits (readme, code style, add you as contributor, maybe fix the 16bit compatibility if needed, ...).

**Comment by QuentinCG** [comment]
@Bu-Gee Thanks again for the pull request.

I don't understand why you need to do all this complex edit for the I2C address of your device.
I'm maybe missing something important but I don't see what...

Here is my logic:
The default I2C address of CAT24C01/02/04/08/16 devices from [datasheet](https://github.com/QuentinCG/Arduino-I2C-EEPROM-library/files/9363752/datasheet.pdf) seems to be **0xA0** (1010 0000 in binary) if A0&A1&A2 are set to GND.

image
(edit: binary is 1010000 => 0x50 in hexa like other EEPROMs)

=> Isn't this working using the existing library (without your edits) ?
```cpp
// CAT24CXX devices:
I2CEEPROM myCat24xxDevice = I2CEEPROM(0x50);
```

If not, the only required edit should be the following edits to be compatible with CAT24C(01)/02/04/08/16:
 - Add a boolean to `I2CEEPROM` constructor to check if the device is a Cat24cxx : 
 ```cpp
I2CEEPROM::I2CEEPROM(int i2c_device_address, bool is_cat24cxx = false);
```
 - Edit read/write function this way (like you did):
  ```cpp
  // In classic device mode, send the 8 MSB of the memory address.  This is already part of the device addr in CAT24CXX
  if(!_isCat24Cxx)
  {
      Wire.write((byte)(address >> 8));   // MSB
  }
```
- We could then call the lib this way;
```cpp
// 24LCxxx devices or any basic devices:
I2CEEPROM(0x50/*, false*/);

// CAT24CXX devices:
I2CEEPROM(0x50, true);
```
----

Other question: What should be added to handle CAT24C01 (1kbit EEPROM) ?

**Comment by Bu-Gee** [comment]
@QuentinCG Unfortunately, the addressing complexity is the only fundamental difference between the 02/04/08/16 and the 128/256/512 devices.

If you look at the Figure that you put in your comment, the 'A' (upper-case A) is the user-chosen I2C address based on the external hardware configuration and the 'a' (lower-case a) is the MSB of the memory address based on the device.  For example, the 16 (kilobit) variant has 2048 addresses, so that is 11 bits.  The 3 MSB of the **MEMORY** address ends up becoming the 3 LSB of the **I2C DEVICE** address, i.e. a10, a9, and a8.  It is almost like the 16 variant has 8 separate cores of the 02 variant with part of the I2C address internally hard-wired.

I did originally think about doing it so that I would just have 8 copies of the EEPROM library, one for each 2 kb of memory, and doing some translation as a shim library, but I feared it would be too expensive in terms of RAM to be able to do that effectively.

To be honest, I'm not 100% sure that it makes sense to have the 02/04/08/16 support in your library because if you're just using the simple 16-bit variant (i.e. 128/256/512), the code is MUCH simpler and that matters on embedded systems.  I won't be mad if it doesn't work in the way you were envisioning and I am happy to continue maintaining it as a fork for as long as I have devices to test with.

**Comment by Bu-Gee** [comment]
I didn't see the question on the first time reading your comment, but the CAT24C01 device should be the same as the 02 variant.  Adding a define for the same as the 02 variant should work.

I wasn't originally aware of the 01 variant.  It looks like ONSemi doesn't like the advertise it in their data sheet since they bought out Catalyst Semi.

**Comment by QuentinCG** [comment]
@Bu-Gee 
Thanks for the explanation !

I merged your pull request + did some edits + added CAT24C01 + tagged the lib as 1.2.0.

Feel free to tell me if you see any issue on this version 👍

**Pull request merged**
